language: php

php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly
  
sudo: false

install:
  - travis_retry composer update --no-progress --prefer-dist --profile

script:
  - composer test
